application:
  name: spring-boot-cassandra-datastax
server:
  port: 8089
  context-path: /student-api
# Following are Cassandra Configuration
cassandra:
  host: 127.0.0.1:9042
  cluster:
    name: test
    username: cassandra
    password: cassandra
  keyspace:
    name: tuturself